In [81]:
from google.colab import drive #Drive bağlı olmasaydı bu şekilde olacaktı
import pandas as pd

drive.mount('/content/drive') #--> Drive'ı bağlama işlemi

file_path = '/content/drive/MyDrive/Acun Medya/Hafta_1/penguins.csv' #--> Drive'dan veriyi çekme işlemi
data = pd.read_csv(file_path) #--> veriyi okuma işlemi

data.head() #--> ilk 5 satırı gösterir

In [112]:
import pandas as pd #--> veri manipülasyonu için kullanılır

#Drive öncesinde bağlı olduğu için mount işlemi gerçekleştirlmedi
data = pd.read_csv('/content/drive/MyDrive/Acun Medya/Hafta_1/penguins.csv') #--> veriyi okuma işlemi yapar
df = pd.DataFrame(data) #--> veriyi dataframe'e dönüştürür

In [113]:
display(df) #--> dataframe'i gösterir

,id,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007
...,...,...,...,...,...,...,...,...,...
339,339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009

NOT:

-->Çıktılar içerisindeki sağ üstte bulunan simgelerden ilki 'Convert this dataframe to an interactive table' butonu tabloyu daha düzgün hale getiriyor.

-->Bir altındaki simge 'Suggest Charts' her tıklandığında çıktısı üretilmiş olan dataframe için çeşitli grafikler üretiyor.

In [114]:
display(df.dtypes) #--> dataframe'in veri tiplerini gösterir

id                     int64
species               object
island                object
bill_length_mm       float64
bill_depth_mm        float64
flipper_length_mm    float64
body_mass_g          float64
sex                   object
year                   int64
dtype: object

In [115]:
df.head() #--> ilk 5 satırı gösterir

,id,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007

In [116]:
df.tail() #--> son 5 satırı gösterir

,id,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
339,339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009

In [117]:
df.info() #--> veriseti hakkında genel bilgi verir

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 344 non-null    int64
 1   species            344 non-null    object
 2   island             344 non-null    object
 3   bill_length_mm     342 non-null    float64
 4   bill_depth_mm      342 non-null    float64
 5   flipper_length_mm  342 non-null    float64
 6   body_mass_g        342 non-null    float64
 7   sex                333 non-null    object
 8   year               344 non-null    int64
dtypes: float64(4), int64(2), object(3)
memory usage: 24.3+ KB

In [118]:
df.describe() #--> veriseti hakkında istatistiksel bilgileri verir

,id,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,year
count,344.000000,342.000000,342.000000,342.000000,342.000000,344.000000
mean,171.500000,43.921930,17.151170,200.915205,4201.754386,2008.029070
std,99.448479,5.459584,1.974793,14.061714,801.954536,0.818356
min,0.000000,32.100000,13.100000,172.000000,2700.000000,2007.000000
25%,85.750000,39.225000,15.600000,190.000000,3550.000000,2007.000000
50%,171.500000,44.450000,17.300000,197.000000,4050.000000,2008.000000
75%,257.250000,48.500000,18.700000,213.000000,4750.000000,2009.000000
max,343.000000,59.600000,21.500000,231.000000,6300.000000,2009.000000

In [119]:
display(df.shape) #--> dataframe'in satır ve sütun sayısını gösterir

(344, 9)

In [120]:
display(df.columns) #--> dataframe'in sütunlarını gösterir

Index(['id', 'species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex', 'year'],
      dtype='object')

In [121]:
display(df.index) #--> dataframe'in satırlarını gösterir

RangeIndex(start=0, stop=344, step=1)

In [122]:
print(df.isnull().sum()) #--> dataframe'deki herbir sütun için null değerlerin toplam kaç adet olduğunu gösterir.

id                    0
species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
year                  0
dtype: int64

In [123]:
display(df.dtypes)
print(df.isnull().sum())

id                     int64
species               object
island                object
bill_length_mm       float64
bill_depth_mm        float64
flipper_length_mm    float64
body_mass_g          float64
sex                   object
year                   int64
dtype: object

id                    0
species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
year                  0
dtype: int64

In [124]:
std_dev = data['bill_length_mm'].std()
print(f'Standart Sapma: {std_dev}')
# --> Sütunun standart sapmasını hesapladık

mean = data['bill_length_mm'].mean()
print(f'Ortalama: {mean}')
# --> Sütunun ortalamasını hesapladık

median = data['bill_length_mm'].median()
print(f'Medyan: {median}')
# --> Sütunun medyanını hesapladık

mode = data['bill_length_mm'].mode()
print(f'Mod: {mode}')
# --> Sütunun modunu hesapladık

Standart Sapma: 5.4595837139265315
Ortalama: 43.9219298245614
Medyan: 44.45
Mod: 0    41.1
Name: bill_length_mm, dtype: float64

In [125]:
# Boş verileri doldurmak için Ortalamayı tercih ettim.

df['bill_length_mm'] = df['bill_length_mm'].fillna(df['bill_length_mm'].mean())
# df['bill_length_mm'].fillna(df['bill_length_mm'].mean(), inplace=True) --> inplace=true kalıcı halde değişikliği gerçekleştirir

In [126]:
df['bill_length_mm'].isnull().sum()

0

In [127]:
std_dev = data['bill_depth_mm'].std()
print(f'Standart Sapma: {std_dev}')
# --> Sütunun standart sapmasını hesapladık

mean = data['bill_depth_mm'].mean()
print(f'Ortalama: {mean}')
# --> Sütunun ortalamasını hesapladık

median = data['bill_depth_mm'].median()
print(f'Medyan: {median}')
# --> Sütunun medyanını hesapladık

mode = data['bill_depth_mm'].mode()
print(f'Mod: {mode}')
# --> Sütunun modunu hesapladık

Standart Sapma: 1.9747931568167818
Ortalama: 17.151169590643274
Medyan: 17.3
Mod: 0    17.0
Name: bill_depth_mm, dtype: float64

In [128]:
# Boş verileri doldurmak için Ortalamayı tercih ettim.

df['bill_depth_mm'] = df['bill_depth_mm'].fillna(df['bill_depth_mm'].mean())
# df['bill_depth_mm'].fillna(df['bill_depth_mm'].mean(), inplace=True) --> inplace=true kalıcı halde değişikliği gerçekleştirir

In [129]:
df['bill_depth_mm'].isnull().sum()

0

In [130]:
std_dev = data['flipper_length_mm'].std()
print(f'Standart Sapma: {std_dev}')
# --> Sütunun standart sapmasını hesapladık

mean = data['flipper_length_mm'].mean()
print(f'Ortalama: {mean}')
# --> Sütunun ortalamasını hesapladık

median = data['flipper_length_mm'].median()
print(f'Medyan: {median}')
# --> Sütunun medyanını hesapladık

mode = data['flipper_length_mm'].mode()
print(f'Mod: {mode}')
# --> Sütunun modunu hesapladık

Standart Sapma: 14.061713679356888
Ortalama: 200.91520467836258
Medyan: 197.0
Mod: 0    190.0
Name: flipper_length_mm, dtype: float64

In [131]:
# Boş verileri doldurmak için Medyan tercih ettim.

df['flipper_length_mm'] = df['flipper_length_mm'].fillna(df['flipper_length_mm'].median())
# df['flipper_length_mm'].fillna(df['flipper_length_mm'].mean(), inplace=True) --> inplace=true kalıcı halde değişikliği gerçekleştirir

In [132]:
df['flipper_length_mm'].isnull().sum()

0

In [133]:
std_dev = data['body_mass_g'].std()
print(f'Standart Sapma: {std_dev}')
# --> Sütunun standart sapmasını hesapladık

mean = data['body_mass_g'].mean()
print(f'Ortalama: {mean}')
# --> Sütunun ortalamasını hesapladık

median = data['body_mass_g'].median()
print(f'Medyan: {median}')
# --> Sütunun medyanını hesapladık

mode = data['body_mass_g'].mode()
print(f'Mod: {mode}')
# --> Sütunun modunu hesapladık

Standart Sapma: 801.9545356980958
Ortalama: 4201.754385964912
Medyan: 4050.0
Mod: 0    3800.0
Name: body_mass_g, dtype: float64

In [134]:
# Boş verileri doldurmak için Medyan tercih ettim.

df['body_mass_g'] = df['body_mass_g'].fillna(df['body_mass_g'].median())
# df['body_mass_g'].fillna(df['body_mass_g'].mean(), inplace=True) --> inplace=true kalıcı halde değişikliği gerçekleştirir

In [135]:
df['body_mass_g'].isnull().sum()

0

In [136]:
    # HESAPLANAMAZ veritipi OBJECT
# --> Sütunun standart sapmasını hesapladık

    # HESAPLANAMAZ veritipi OBJECT
# --> Sütunun ortalamasını hesapladık

    # HESAPLANAMAZ veritipi OBJECT
# --> Sütunun medyanını hesapladık

mode = data['sex'].mode()
print(f'Mod: {mode}')
# --> Sütunun modunu hesapladık

Mod: 0    male
Name: sex, dtype: object

In [137]:
print(df['sex'].mode())
print(type(df['sex'].mode()))
  # Mode fonksiyonu içerisinden dönen değer pandas serisi olarak görülüyor.
  # Bu nedenle de fillna() fonksiyonu ile boşlukları doldururken bir ince detay gerekiyor

0    male
Name: sex, dtype: object
<class 'pandas.core.series.Series'>

In [138]:
# Boş verileri doldurmak için Mod tercih ettim.

df['sex'] = df['sex'].fillna(df['sex'].mode()[0]) # --> Pandas Serisi olduğunu biliyoruz, buna dayanarak da serinin ilk değerini talep ediyoruz
# df['sex'].fillna(df['sex'].mean(), inplace=True) #--> inplace=true kalıcı halde değişikliği gerçekleştirir

In [139]:
df['sex'].isnull().sum()

0

In [140]:
display(df)

,id,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,0,Adelie,Torgersen,39.10000,18.70000,181.0,3750.0,male,2007
1,1,Adelie,Torgersen,39.50000,17.40000,186.0,3800.0,female,2007
2,2,Adelie,Torgersen,40.30000,18.00000,195.0,3250.0,female,2007
3,3,Adelie,Torgersen,43.92193,17.15117,197.0,4050.0,male,2007
4,4,Adelie,Torgersen,36.70000,19.30000,193.0,3450.0,female,2007
...,...,...,...,...,...,...,...,...,...
339,339,Chinstrap,Dream,55.80000,19.80000,207.0,4000.0,male,2009
340,340,Chinstrap,Dream,43.50000,18.10000,202.0,3400.0,female,2009
341,341,Chinstrap,Dream,49.60000,18.20000,193.0,3775.0,male,2009
342,342,Chinstrap,Dream,50.80000,19.00000,210.0,4100.0,male,2009
343,343,Chinstrap,Dream,50.20000,18.70000,198.0,3775.0,female,2009

In [143]:
print(df.isnull().sum())

# Tüm boş değerler giderildi.

id                   0
species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
year                 0
dtype: int64

In [142]:
print(df['sex'])

0        male
1      female
2      female
3        male
4      female
        ...
339      male
340    female
341      male
342      male
343    female
Name: sex, Length: 344, dtype: object

In [144]:
df['sex'].unique()

array(['male', 'female'], dtype=object)

In [ ]:
# sex sütunu için ENCODİNG işlemi gerçekleştirilmesi:
# Mekine öğrenmesi sayısal veriler ile daha iyi ve hızlı analiz gerçekleştirir.

df['sex'] = df['sex'].map({'male': 0, 'female': 1})

In [147]:
display(df)

,id,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,0,Adelie,Torgersen,39.10000,18.70000,181.0,3750.0,0,2007
1,1,Adelie,Torgersen,39.50000,17.40000,186.0,3800.0,1,2007
2,2,Adelie,Torgersen,40.30000,18.00000,195.0,3250.0,1,2007
3,3,Adelie,Torgersen,43.92193,17.15117,197.0,4050.0,0,2007
4,4,Adelie,Torgersen,36.70000,19.30000,193.0,3450.0,1,2007
...,...,...,...,...,...,...,...,...,...
339,339,Chinstrap,Dream,55.80000,19.80000,207.0,4000.0,0,2009
340,340,Chinstrap,Dream,43.50000,18.10000,202.0,3400.0,1,2009
341,341,Chinstrap,Dream,49.60000,18.20000,193.0,3775.0,0,2009
342,342,Chinstrap,Dream,50.80000,19.00000,210.0,4100.0,0,2009
343,343,Chinstrap,Dream,50.20000,18.70000,198.0,3775.0,1,2009

In [152]:
# get_dummies ile çözümü:

df_dummies = pd.get_dummies(df, columns=['sex'], drop_first=False)
df_dummies.head()

# sex_0 ve sex_1 olmak üzere iki adet sütuna parçalıyor aslında

,id,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,year,sex_0,sex_1
0,0,Adelie,Torgersen,39.10000,18.70000,181.0,3750.0,2007,True,False
1,1,Adelie,Torgersen,39.50000,17.40000,186.0,3800.0,2007,False,True
2,2,Adelie,Torgersen,40.30000,18.00000,195.0,3250.0,2007,False,True
3,3,Adelie,Torgersen,43.92193,17.15117,197.0,4050.0,2007,True,False
4,4,Adelie,Torgersen,36.70000,19.30000,193.0,3450.0,2007,False,True

In [156]:
df_dummies['sex_0'].dtype

dtype('bool')

Modeli Eğitme Kısmı:

In [157]:
features = df[['island', 'bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'body_mass_g', 'year']] # --> Bağımsız değişkenler
label = df['species'] # --> Bağımlı değişken

display(features.head())
display(label.head())

,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,year
0,Torgersen,39.10000,18.70000,181.0,3750.0,2007
1,Torgersen,39.50000,17.40000,186.0,3800.0,2007
2,Torgersen,40.30000,18.00000,195.0,3250.0,2007
3,Torgersen,43.92193,17.15117,197.0,4050.0,2007
4,Torgersen,36.70000,19.30000,193.0,3450.0,2007

0    Adelie
1    Adelie
2    Adelie
3    Adelie
4    Adelie
Name: species, dtype: object

Eğitim Veriseti ve Test Verisetinin Belirlenmesi:

In [158]:
from sklearn.model_selection import train_test_split
# x: bağımsız değişkenler
# y: bağımlı değişken

x_train, x_test, y_train, y_test = train_test_split(features, label, test_size=0.2, random_state=42)

# x_train bağımsız değişken eğitim verileri %80
# x_test bağımsız değişken test verileri %20
# y_train bağımlı değişken eğitim veri seti %80
# y_test bağımlı değişken test veri seti %20

print("\nEğitim ve Test Seti Boyutları:")
print("X_train:", x_train.shape)
print("X_test:", x_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

Eğitim ve Test Seti Boyutları:
X_train: (275, 6)
X_test: (69, 6)
y_train: (275,)
y_test: (69,)